Bootstrap: docker
From: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

%post
    apt-get update && apt-get install -y --no-install-recommends \
    python3.6 \
    python3-pip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

    pip3 install --upgrade pip

    apt-get update -y
    apt-get install -y git

    apt-get install libgtk2.0-dev -y

    python3 -m pip install attrs==19.3.0
    python3 -m pip install black==19.3b0
    python3 -m pip install cmake==3.16.3
    python3 -m pip install setuptools
    python3 -m pip install efficientnet-pytorch==0.5.1
    python3 -m pip install gdown==3.10.2
    python3 -m pip install got10k==0.1.3
    python3 -m pip install h5py==2.10.0
    python3 -m pip install imageio==2.6.1
    python3 -m pip install imageio-ffmpeg==0.3.0
    python3 -m pip install numpy==1.18.1
    python3 -m pip install opencv-python==4.1.0.25
    python3 -m pip install Pillow==7.0.0
    python3 -m pip install PyYAML==5.3
    python3 -m pip install scikit-image==0.16.2
    python3 -m pip install scikit-learn==0.21.2
    python3 -m pip install scipy==1.3.2
    python3 -m pip install torch==1.4.0
    python3 -m pip install torchvision==0.5.0
    python3 -m pip install tqdm==4.32.2
    python3 -m pip install yacs==0.1.6
    python3 -m pip install youtube-dl==2020.1.24
    python3 -m pip install git+https://github.com/danielgordon10/dg_util.git
    python3 -m pip install MulticoreTSNE

    mkdir datasets