Bootstrap: docker
From: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

%post
    apt-get update && apt-get install -y --no-install-recommends \
    python3.8 \
    python3-pip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

    pip3 install attrs==19.3.0
    pip3 install black==19.3b0
    pip3 install cmake==3.16.3
    pip3 install efficientnet-pytorch==0.5.1
    pip3 install gdown==3.10.2
    pip3 install got10k==0.1.3
    pip3 install h5py==2.10.0
    pip3 install imageio==2.6.1
    pip3 install imageio-ffmpeg==0.3.0
    pip3 install numpy==1.18.1
    pip3 install opencv-python==4.1.0.25
    pip3 install Pillow==7.0.0
    pip3 install PyYAML==5.3
    pip3 install scikit-image==0.16.2
    pip3 install scikit-learn==0.21.2
    pip3 install scipy==1.3.2
    pip3 install torch==1.4.0
    pip3 install torchvision==0.5.0
    pip3 install tqdm==4.32.2
    pip3 install yacs==0.1.6
    pip3 install youtube-dl==2020.1.24
    pip3 install git+https://github.com/danielgordon10/dg_util.git
    pip3 install MulticoreTSNE

    mkdir datasets